version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - directory: "/"
    package-ecosystem: "gradle"
    schedule:
      interval: "daily"
  - directory: "/ImGuiApplication"
    package-ecosystem: "gradle"
    schedule:
      interval: "daily"
